# Generated by Django 2.2.6 on 2019-10-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('cellphone', models.BigIntegerField()),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cloth', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value_work', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value_threads', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_buttons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_necks', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('value_embroidery', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('value_prints', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fashion', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='confma.User')),
            ],
        ),
    ]
