# Generated by Django 2.2.6 on 2020-02-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='test',
        ),
    ]
