# Generated by Django 2.2.6 on 2019-10-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='user',
        ),
    ]
