# Generated by Django 2.2.6 on 2019-12-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma.Cloth'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_buttons',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_cloth',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_embroidery',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_necks',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_prints',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_threads',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='value_work',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
