# Generated by Django 2.2.6 on 2019-11-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Cotizacion_User',
        ),
    ]
