# Generated by Django 2.2.6 on 2019-12-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0002_auto_20191209_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cloth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.Cloth'),
            preserve_default=False,
        ),
    ]
