# Generated by Django 2.2.6 on 2019-10-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0002_auto_20191013_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.SmallIntegerField(),
        ),
    ]
