# Generated by Django 2.2.6 on 2019-10-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0002_remove_cotizacion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='total',
        ),
    ]
