# Generated by Django 2.2.6 on 2020-02-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.Photo'),
            preserve_default=False,
        ),
    ]
