# Generated by Django 2.2.6 on 2019-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0003_auto_20191026_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='state',
            field=models.SmallIntegerField(default=1),
        ),
    ]
