# Generated by Django 2.2.6 on 2019-12-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0003_cotizacion_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')], default=1),
        ),
    ]
