# Generated by Django 2.2.6 on 2019-12-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0004_auto_20191209_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], default=1),
        ),
    ]
