# Generated by Django 2.2.6 on 2019-10-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0004_auto_20191013_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
