# Generated by Django 2.2.6 on 2019-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0005_auto_20191013_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
