# Generated by Django 2.2.6 on 2019-12-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0005_auto_20191209_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cloth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.Cloth'),
        ),
    ]
