# Generated by Django 2.2.6 on 2020-02-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0005_remove_cloth_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='static/fashion/notfound.jpg', upload_to='static/fashion'),
        ),
    ]
