# Generated by Django 2.2.6 on 2020-02-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0006_cloth_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
