# Generated by Django 2.2.6 on 2019-12-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0006_auto_20191209_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateField()),
                ('date_return', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma.Cloth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma.User')),
            ],
        ),
    ]
