# Generated by Django 2.2.6 on 2019-10-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0006_auto_20191013_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cloth', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value_work', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value_threads', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_buttons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_necks', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('value_embroidery', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('value_prints', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fashion', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma.User')),
            ],
        ),
    ]
