# Generated by Django 2.2.6 on 2020-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0007_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='static/fashion/notfound.jpg', upload_to='media/fashion'),
        ),
    ]
