# Generated by Django 2.2.6 on 2019-10-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0007_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='user_id',
            new_name='user',
        ),
    ]
