# Generated by Django 2.2.6 on 2019-12-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0007_alquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='date_now',
            field=models.DateField(auto_now_add=True),
        ),
    ]
