# Generated by Django 2.2.6 on 2020-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0009_auto_20200206_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='media/notfound.jpg', upload_to='fashion'),
        ),
    ]
