# Generated by Django 2.2.6 on 2020-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0011_auto_20200206_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='fashion'),
        ),
    ]
