# Generated by Django 2.2.6 on 2020-02-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0012_auto_20200206_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotizacion_Client',
            new_name='CotizacionClient',
        ),
    ]
