# Generated by Django 2.2.6 on 2020-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0013_auto_20200207_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='fashion/%Y/%m/%d/'),
        ),
    ]
