# Generated by Django 2.2.6 on 2020-02-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0014_auto_20200208_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='ifrental',
            field=models.SmallIntegerField(default=1),
        ),
    ]
