# Generated by Django 2.2.6 on 2020-03-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('cellphone', models.BigIntegerField()),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=1, max_length=10)),
                ('fashion', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='fashion/%Y/%m/%d/')),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cloth', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value_work', models.DecimalField(decimal_places=2, max_digits=9)),
                ('value_threads', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_buttons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_necks', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('value_embroidery', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('value_prints', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma_api.Client')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma_api.Cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='client',
            field=models.ManyToManyField(through='confma_api.CotizacionClient', to='confma_api.Client'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma_api.Cloth'),
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateField(auto_now_add=True)),
                ('date_return', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('ifrental', models.SmallIntegerField(default=1)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma_api.Client')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confma_api.Cloth')),
            ],
        ),
    ]
